# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86e10b0dc355eb1a0d08d9faef01bc3eee58d9cef659812ff61a8c3e689508431184ce6731274afbe238110d95849895b981ac99ff42127c3dfc043f4da662af

test:
  secret_key_base: ce4009380a4e069e97a63f63a4d376b607e18357c07d31ad51de9c51c9faeddef8c1d430c5888019cccdeb6960b126cbb904bfe421738b43f66b9dc31e80e7da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
