# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2b4740c9aae8302c33fe3cce19352722ddc5727f1c2a754b00531b8dd3efe837a5f843e7af22cd636ad6d0dea58c6e9375e9ea8a05f7f19f0f0bb2ab364e87e

test:
  secret_key_base: 66da1ba64c246523ba139624616c436d9b95aaa76b6c4b6da39e127f4f3583f6a9c24cc44efe03f6e2a55957fb31011eeebcf6810c35f3131003ff5ea7b9b511

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
