# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bba7cba35336439bdde231e8bedc8ebb38a3a16213e247c563e31d9434f9af6b55269b5060db648fe3164707660753aa15733232b7825189f939f2c75d72afe

test:
  secret_key_base: b7aa8d1fbac723dff008f6ab2f3431763254c4e95d2db00b73e7169865a82e4da60cb31186c4e257fa16734e77c9d0c16b83806a426ac4e3a68e6eb57b9e9116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
